name: Push-to-Ec2
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:17.0.2
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Connect to ece2
        run: |
          ls -la && pwd         
          cd ./tf-example
          chmod 600 myjune222key.pem
          cd /tf-example && chmod 600 myJune222Key.pem
          ssh -i "myJune222Key.pem" ubuntu@ec2-3-131-96-136.us-east-2.compute.amazonaws.com
