name: Push-to-Ec2
on:
  push:
    branches:
      - develop
  workflow_dispatch:    
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:17.0.2
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Connect to ece2
        shell: bash
        run: |
          ls -la && pwd         
          cd ./tf-example && sudo chmod u+x myJune222Key.pem && sudo ssh -tt -o StrictHostKeyChecking=no -i myJune222Key.pem ubuntu@ec2-3-17-204-144.us-east-2.compute.amazonaws.com
        env:
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}  
