name: Push-to-Ec2
on:
  workflow_dispatch:
    inputs:
      run-commands:
        description: runcommands
        required: true
        default: 'carmacloudcomands'
        type: string    
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            TARGET: ${{ secrets.TARGET_DIR }}  
      - name: Run CC comands 
        run: |
          ls -la
          pwd
