name: Push-to-Ec2
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:17.0.2
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Connect to ece2
        run: |
          ls -la && pwd         
          cd ./tf-example && sudo chmod u+x myJune222Key.pem &&  ssh -i "${{ secrets.EC2_SSH_KEY }}" -tt -R ubuntu@ec2-3-131-96-136.us-east-2.compute.amazonaws.com
