name: Carmacloud-test
on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: EC2 name
        required: true
        default: 'carmacloud-test'
        type: string
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: us-east-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id:   apply
        env:
          TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        run: |
          cd tf-example/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
          echo "public_dns=$(echo $public_dns | cut -c 1-6)" >> ${{ secrets.HOST_DNS }}   
          
  #PushtoEC2Instance:
    #runs-on: ubuntu-latest
    #steps:
      #- name: Checkout the code
        #uses: actions/checkout@v1
      #- name: Deploy to my EC2 instance
        #uses: easingthemes/ssh-deploy@v2.1.5
        #env:
          #SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          #SOURCE: "./"
          #REMOTE_HOST: "ec2-34-213-48-149.us-west-2.compute.amazonaws.com"
          #REMOTE_USER: "ec2-user"
          #TARGET: "/home/ec2-user/SampleExpressApp"          

      #- name: Terraform destroy
        #id: destroy
        #env:
          #TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        #run: |
          #cd tf-example/
          #terraform destroy -auto-approve
